# -*- coding: utf-8 -*-
"""research paper - ad and ha

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYVm4QstOoBdd5DstHMwfLjZz4jTWqfG
"""

print(f"Pandas version: {pd.__version__}")
print(f"Numpy version: {np.__version__}")
import matplotlib # Import matplotlib explicitly to get its version
print(f"Matplotlib version: {matplotlib.__version__}")
print(f"Seaborn version: {sns.__version__}")

# % Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams["figure.dpi"] = 120
sns.set_style("whitegrid")

# % Load Data
sim = pd.read_csv("Similiar_intersections.csv")
rnd = pd.read_csv("Roundabouts.csv")

# Intersection type labeled
sim["Intersection_Type"] = "Non-Roundabout"
rnd["Intersection_Type"] = "Roundabout"

# Combine datasets
df = pd.concat([sim, rnd], ignore_index=True)

# % Basic Sanity Checks
print("Sample sizes:")
print(df["Intersection_Type"].value_counts())

print("\nKey columns:")
print(df.columns)

# % Crash Rate Comparison (Essentially how effective)
crash_summary = df.groupby("Intersection_Type")["rate_TOTAL_CRASHES"].describe()
print(crash_summary)

# Boxplot for visual comparison
plt.figure()
sns.boxplot(
    data=df,
    x="Intersection_Type",
    y="rate_TOTAL_CRASHES"
)
plt.title("Crash Rate Comparison: Roundabouts vs Non-Roundabouts")
plt.ylabel("Crash Rate (Exposure-Adjusted)")
plt.xlabel("")
plt.show()

# % Exposure & Traffic Context
exposure_summary = df.groupby("Intersection_Type")[[
    "AADTR_mean",
    "Exposure_5YR_MEV"
]].mean()

print(exposure_summary)

# % Socioeconomic Comparison
socio_summary = df.groupby("Intersection_Type")[[
    "Median_HH_Income",
    "Pct_Below_Poverty"
]].mean()

print(socio_summary)

# % Socioeconomic Distribution Plots
plt.figure()
sns.boxplot(
    data=df,
    x="Intersection_Type",
    y="Median_HH_Income"
)
plt.title("Median Household Income by Intersection Type")
plt.ylabel("Median Household Income ($)")
plt.xlabel("")
plt.show()

plt.figure()
sns.boxplot(
    data=df,
    x="Intersection_Type",
    y="Pct_Below_Poverty"
)
plt.title("Poverty Rate by Intersection Type")
plt.ylabel("Percent Below Poverty Line")
plt.xlabel("")
plt.show()

# %% Correlation Heatmap (Crash + Socioeconomic)
corr_vars = [
    "rate_TOTAL_CRASHES",
    "Median_HH_Income",
    "Pct_Below_Poverty",
    "AADTR_mean",
    "Exposure_5YR_MEV"
]

corr_matrix = df[corr_vars].corr()

plt.figure(figsize=(7,6))
sns.heatmap(
    corr_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f",
    linewidths=0.5
)
plt.title("Correlation Heatmap: Crashes, Traffic, and Socioeconomic Factors")
plt.show()

# %% Focused Correlation by Intersection Type
round_corr = df[df["Intersection_Type"] == "Roundabout"][corr_vars].corr()
nonround_corr = df[df["Intersection_Type"] == "Non-Roundabout"][corr_vars].corr()

plt.figure(figsize=(14,5))

plt.subplot(1,2,1)
sns.heatmap(round_corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Roundabouts: Correlation Structure")

plt.subplot(1,2,2)
sns.heatmap(nonround_corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Non-Roundabouts: Correlation Structure")

plt.tight_layout()
plt.show()